name: chat
description: Chat app with Flutter and Firebase.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  firestore_repository:
    path: packages/firestore_repository
  local_cache:
    path: packages/local_cache
  message_selector:
    path: packages/message_selector
  bloc: ^8.1.2
  equatable: ^2.0.3
  flow_builder: ^0.0.9
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.4.0
  formz: ^0.6.0
  intl: ^0.18.1
  fluttertoast: ^8.0.9
  go_router: ^7.0.2
  boxy: ^2.0.9
  sliver_tools: ^0.2.10
  firebase_core: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
