name: local_cache
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  drift: ^2.0.2+1
  path: ^1.8.1
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.9

dev_dependencies:
  build_runner: ^2.3.2
  drift_dev: ^2.0.2
  lints: ^2.0.0
  # test: ^1.16.0
