name: local_cache
version: 1.0.0

environment:
  sdk: ^3.0.1

dependencies:
  build_config: ^1.1.1
  drift: ^2.8.0
  path: ^1.8.3
  path_provider: ^2.0.15
  sqlite3_flutter_libs: ^0.5.15

dev_dependencies:
  build_runner: ^2.4.4
  drift_dev: ^2.8.2
  lints: ^2.0.0
  test: ^1.21.0
